from __future__ import annotations

from typing import Dict

import torch
from PIL import Image
from pydantic import BaseModel
from torchvision import transforms

from app.config import (
    CLASS_NAMES,
    DEVICE,
    IMAGE_SIZE,
    MEAN,
    STD,
)


class PredictionResult(BaseModel):
    prediction: str
    confidence: float
    probabilities: Dict[str, float]
    disclaimer: str


class InferencePipeline:
    """
    Vision Transformer inference pipeline for ASD screening.
    """

    def __init__(self, model):
        self.model = model
        self.device = DEVICE

        self.transform = transforms.Compose(
            [
                transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
                transforms.ToTensor(),
                transforms.Normalize(
                    mean=MEAN,
                    std=STD,
                ),
            ]
        )

    @torch.inference_mode()
    def predict(self, image: Image.Image) -> PredictionResult:

        image = image.convert("RGB")

        tensor = self.transform(image)
        tensor = tensor.unsqueeze(0).to(self.device)

        logits = self.model(tensor)

        probs = torch.softmax(logits, dim=1)[0]

        confidence, predicted = torch.max(probs, dim=0)

        probabilities = {
            CLASS_NAMES[i]: round(float(probs[i]) * 100, 2)
            for i in range(len(CLASS_NAMES))
        }

        return PredictionResult(
            prediction=CLASS_NAMES[predicted.item()],
            confidence=round(float(confidence) * 100, 2),
            probabilities=probabilities,
            disclaimer=(
                "This result is generated by a research prototype and "
                "is not a medical diagnosis. Please consult a qualified "
                "healthcare professional for clinical evaluation."
            ),
        )